use hr_db;

CREATE TABLE job_grades(
GRADE_LEVEL varchar(2) NOT NULL,
LOWEST_SAL LONG NULL,
HIGHEST_SAL LONG NULL,
CONSTRAINT PK_job_grades PRIMARY KEY (GRADE_LEVEL)
);

CREATE TABLE jobs(
JOB_ID VARCHAR(10) NOT NULL,
JOB_TITLE VARCHAR(35) NULL,
MIN_SALARY LONG NULL,
MAX_SALARY LONG NULL,
CONSTRAINT PK_jobs PRIMARY KEY(JOB_ID)
);

CREATE TABLE regions(
REGION_ID numeric NOT NULL,
REGION_NAME VARCHAR(25) NULL,
CONSTRAINT PK_regions PRIMARY KEY(REGION_ID)
);

CREATE TABLE countries(
COUNTRY_ID CHAR(2) NOT NULL,
COUNTRY_NAME VARCHAR(40) NULL,
REGION_ID NUMERIC NULL,
CONSTRAINT PK_countries PRIMARY KEY(COUNTRY_ID),
CONSTRAINT FK_countries FOREIGN KEY(REGION_ID) REFERENCES regions(REGION_ID)
);

CREATE TABLE locations(
LOCATION_ID NUMERIC NOT NULL,
STREET_ADDRESS VARCHAR(25) NULL,
POSTAL_CODE VARCHAR(12) NULL,
CITY VARCHAR(30) NULL,
STATE_PROVINCE VARCHAR(12) NULL,
COUNTRY_ID CHAR(2) NOT NULL,
CONSTRAINT PK_locations PRIMARY KEY(LOCATION_ID),
CONSTRAINT FK_locations FOREIGN KEY(COUNTRY_ID) 
REFERENCES countries(COUNTRY_ID)
);
CREATE TABLE departments(
DEPARTMENT_ID NUMERIC NOT NULL,
DEPARTMENT_NAME VARCHAR(30) NULL,
MANAGER_ID NUMERIC NOT NULL,
LOCATION_ID NUMERIC NOT NULL,
CONSTRAINT PK_departments PRIMARY KEY(DEPARTMENT_ID),
CONSTRAINT FK_departments FOREIGN KEY(LOCATION_ID) REFERENCES locations(LOCATION_ID)
);
CREATE TABLE employees(
EMPLOYEE_ID NUMERIC NOT NULL,
FIRST_NAME VARCHAR(20)  NULL,
LAST_NAME VARCHAR(25) NULL,
EMAIL VARCHAR(25) NULL,
PHONE_NUMBER VARCHAR(20) NULL,
HIRE_DATE DATE NULL,
JOB_ID VARCHAR(10) NOT NULL,
SALARY NUMERIC NULL,
COMMISSION_PCT DOUBLE NULL,
MANAGER_ID NUMERIC NOT NULL,
DEPARTMENT_ID NUMERIC NOT NULL,
CONSTRAINT PK_employees PRIMARY KEY(EMPLOYEE_ID),
CONSTRAINT FK_emloyees1 FOREIGN KEY(DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID),
CONSTRAINT FK_emloyees FOREIGN KEY(JOB_ID)  REFERENCES jobs(JOB_ID)
);

CREATE TABLE job_history(
EMPLOYEE_ID NUMERIC NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NULL,
JOB_ID VARCHAR(10) NOT NULL,
DEPARTMENT_ID NUMERIC NOT NULL,
CONSTRAINT PK_job_history PRIMARY KEY(EMPLOYEE_ID,START_DATE),
CONSTRAINT FK_job_history1 FOREIGN KEY(DEPARTMENT_ID) REFERENCES departments(DEPARTMENT_ID),
CONSTRAINT FK_job_history FOREIGN KEY(JOB_ID)  REFERENCES jobs(JOB_ID)
);